version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: echo "this is not a test"
          name: Test
  deploy:
    steps:
      - run:
          command: echo "deploy?"
          name: Placeholder

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
